logistics:
  test: false
  revenueDropPercentage:
    below30minutes: 0
    below60minutes: 10
    below120minutes: 20
    above120minutes: 30
logging:
  level:
    org:
      springframework:
        security: debug
spring:
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/webuni
    username: postgres
    password: