hr:
  test: false
  raise:
    def:
      percent: 5
    smart:
      years:    40, 30, 20, 10, 5, 2.5
      percents: 40, 30, 20, 10, 5, 2
spring:
  profiles:
    active: smart
  thymeleaf:  
    cache: false 
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/webuni
    username: postgres
    password: